import cors from "cors";
import express, { ErrorRequestHandler } from "express";
import { globalErrorHandler } from "./middleware/error.middleware";
import authRoutes from "./modules/auth/auth.route";
import categoryRoutes from "./modules/category/category.route";
import userRoutes from "./modules/user/user.route";
import expenseRoutes from "./modules/expense/expense.route";
import incomeRoutes from "./modules/income/income.route";
import budgetRoutes from "./modules/budget/budget.route";
import recurringExpenseRoutes from "./modules/recurringExpense/recurringExpense.route";
import aiRoutes from "./modules/ai/ai.route";
import helmet from "helmet";
import { globalRateLimiter } from "./middleware/rateLimiter";

const app = express();
app.set("trust proxy", 1);
app.use(helmet());
app.use(cors());
app.use(globalRateLimiter);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/api/auth", authRoutes);
app.use("/api/user", userRoutes);
app.use("/api/category", categoryRoutes);
app.use("/api/expense", expenseRoutes);
app.use("/api/income", incomeRoutes);
app.use("/api/budget", budgetRoutes);
app.use("/api/recurring-expense", recurringExpenseRoutes);
app.use("/api/ai", aiRoutes);
app.use(globalErrorHandler as ErrorRequestHandler);

export default app;
